title: GSS Robotics
description: Join 5+ nerdy teenagers who make barely functioning robots in the area’s worst FTC robotics team.
url: "https://gssrobotics.github.io"
social:
  name: Bear Necessities
  links:
    - https://github.com/gssrobotics
    - https://www.youtube.com/@gssrobotics
    - https://ftcscout.org/teams/27330
logo: /assets/graphics/robotics.svg

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: null

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - package.json
  - package-lock.json
  - "*.log"